[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"
default_command = "/media/serban/data/workplace/sources/polkadot-sdk/target/release/polkadot"

[[relaychain.node_groups]]
name = "validator"
count = 3
args = ["--log=beefy=debug", "--enable-offchain-indexing=true"]

[[relaychain.nodes]]
name = "validator-unstable"
args = ["--log=beefy=debug", "--enable-offchain-indexing=true"]
